digapp:
  build: dist
  ports:
    - "8080:8080"
  links:
    - mongo
  environment:
    EUI_SERVER_URL: 'http://127.0.0.1'
    EUI_SERVER_PORT: '80'
    IMAGE_SIM_URL: 'http://127.0.0.1'
    IMAGE_SIM_PORT: '80'
    EUI_SEARCH_INDEX: 'dig-latest'
    BLUR_IMAGES: 'false'
    MONGOHQ_URL: 'mongodb://mongo/dig'
    NODE_ENV: 'production'

nginx:
  image: nginx
  links:
    - digapp
  ports:
    - "80:80"
  volumes:
    - ./conf/nginx/.htpasswd:/etc/nginx/.htpasswd
    - ./conf/nginx_sites_enabled:/etc/nginx/conf.d
    - ./logs/nginx:/var/log/nginx

mongo:
  image: mongo
  volumes_from:
    - mongodata

mongodata:
  image: busybox
  volumes:
    - /data/db/