digapp:
  build: dist
  ports:
    - "8080:8080"
  links:
    - mongo
  environment:
    EUI_SERVER_URL: 'http://127.0.0.1'
    EUI_SERVER_PORT: '80'
    IMAGE_SIM_URL: 'http://127.0.0.1'
    IMAGE_SIM_PORT: '80'
    EUI_SEARCH_INDEX: 'dig-latest'
    BLUR_IMAGES: 'false'
    MONGOHQ_URL: 'mongodb://mongo/dig'
    NODE_ENV: 'production'

notifyapp:
  build: distnotify
  links:
    - mysql
  environment:
    NODE_ENV: 'production'
    DB_USER: 'digapp'
    DB_PASS:
    DB_HOST: 'mysql'
    DB_PORT: 3306
    ES_USER: 'memex'
    ES_PASS: 
    EUI_SERVER: 
    EUI_SERVER_PORT: 
    EUI_SEARCH_INDEX: 'dig-latest'
    EUI_SEARCH_TYPE: 'WebPage'

mysql:
  image: mysql
  volumes_from:
    - mysqldata
  environment:
    MYSQL_ROOT_PASSWORD: 
    MYSQL_DATABASE: 'digapp_production'
    MYSQL_USER: 'digapp'
    MYSQL_PASSWORD: 

mysqldata:
  image: busybox
  volumes: 
    - /var/lib/mysql

nginx:
  image: nginx
  links:
    - digapp
  ports:
    - "80:80"
  volumes:
    - ./conf/nginx/.htpasswd:/etc/nginx/.htpasswd
    - ./conf/nginx_sites_enabled/dig:/etc/nginx/conf.d/default.conf
    - ./logs/nginx:/var/log/nginx

mongo:
  image: mongo
  volumes_from:
    - mongodata

mongodata:
  image: busybox
  volumes:
    - /data/db/